# Generated by Django 4.2.7 on 2025-11-06 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
        ('multitenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_contrato', models.CharField(max_length=50, verbose_name='Número de Contrato')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Contrato')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo_servicio', models.CharField(choices=[('fotografia', 'Servicio Fotografía'), ('enmarcado', 'Enmarcado'), ('graduaciones', 'Graduaciones'), ('laser', 'Corte Láser'), ('evento', 'Evento'), ('personalizado', 'Personalizado')], max_length=20, verbose_name='Tipo de Servicio')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total')),
                ('adelanto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Adelanto')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Pendiente')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('documento_contrato', models.FileField(blank=True, null=True, upload_to='contratos/', verbose_name='Documento del Contrato')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='clientes.cliente', verbose_name='Cliente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multitenancy.tenant', verbose_name='Estudio Fotográfico')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-creado_en'],
                'unique_together': {('tenant', 'numero_contrato')},
            },
        ),
        migrations.CreateModel(
            name='PagoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('yape', 'Yape'), ('plin', 'Plin'), ('otro', 'Otro')], max_length=20, verbose_name='Método de Pago')),
                ('numero_operacion', models.CharField(blank=True, max_length=100, verbose_name='Número de Operación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='contratos.contrato')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por')),
            ],
            options={
                'verbose_name': 'Pago de Contrato',
                'verbose_name_plural': 'Pagos de Contrato',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='EstadoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], max_length=20, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], max_length=20, verbose_name='Estado Nuevo')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo del Cambio')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado Por')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Estado de Contrato',
                'verbose_name_plural': 'Estados de Contrato',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='ClausulaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_clausula', models.PositiveIntegerField(verbose_name='Número de Cláusula')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Cláusula')),
                ('contenido', models.TextField(verbose_name='Contenido de la Cláusula')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clausulas', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Cláusula de Contrato',
                'verbose_name_plural': 'Cláusulas de Contrato',
                'ordering': ['numero_clausula'],
                'unique_together': {('contrato', 'numero_clausula')},
            },
        ),
    ]
