# Generated by Django 4.2.7 on 2025-11-06 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('multitenancy', '0001_initial'),
        ('pedidos', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_op', models.CharField(max_length=20, verbose_name='Número de OP')),
                ('descripcion', models.TextField(verbose_name='Descripción del Trabajo')),
                ('tipo', models.CharField(choices=[('enmarcado', 'Enmarcado'), ('minilab', 'Minilab'), ('graduacion', 'Graduación'), ('corte_laser', 'Corte Láser'), ('edicion_digital', 'Edición Digital'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Producción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('terminado', 'Terminado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20, verbose_name='Prioridad')),
                ('fecha_estimada', models.DateField(verbose_name='Fecha Estimada de Finalización')),
                ('fecha_inicio_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio Real')),
                ('fecha_finalizacion_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización Real')),
                ('notas_operario', models.TextField(blank=True, verbose_name='Notas del Operario')),
                ('materiales_utilizados', models.JSONField(blank=True, default=dict, verbose_name='Materiales Utilizados')),
                ('tiempo_estimado_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tiempo Estimado (horas)')),
                ('tiempo_real_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tiempo Real (horas)')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion', to='clientes.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('operario', models.ForeignKey(limit_choices_to={'role': 'operario'}, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Operario Asignado')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion', to='pedidos.order', verbose_name='Pedido')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_produccion', to='multitenancy.tenant', verbose_name='Estudio Fotográfico')),
            ],
            options={
                'verbose_name': 'Orden de Producción',
                'verbose_name_plural': 'Órdenes de Producción',
                'ordering': ['-creado_en'],
                'unique_together': {('tenant', 'numero_op')},
            },
        ),
    ]
