# Generated by Django 4.2.7 on 2025-11-06 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('core', '0005_alter_rolepermission_role_alter_user_role'),
        ('commerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_op', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('Enmarcado', 'Enmarcado'), ('Minilab', 'Minilab'), ('Graduación', 'Graduación'), ('Corte Láser', 'Corte Láser'), ('Edición Digital', 'Edición Digital'), ('Otro', 'Otro')], max_length=20)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Terminado', 'Terminado'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Normal', 'Normal'), ('Media', 'Media'), ('Alta', 'Alta')], default='Normal', max_length=20)),
                ('fecha_estimada', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='crm.client')),
                ('id_inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='core.tenant')),
                ('operario', models.ForeignKey(limit_choices_to={'role': 'operario'}, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='commerce.order')),
            ],
            options={
                'verbose_name': 'Orden de Producción',
                'verbose_name_plural': 'Órdenes de Producción',
                'ordering': ['-creado_en'],
            },
        ),
    ]
