# Generated by Django 4.2.16 on 2025-11-05 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Evento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('tipo_evento', models.CharField(choices=[('reunion', 'Reunión'), ('llamada', 'Llamada'), ('visita', 'Visita'), ('tarea', 'Tarea'), ('recordatorio', 'Recordatorio'), ('otro', 'Otro')], default='reunion', max_length=20, verbose_name='Tipo de Evento')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha y Hora de Inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha y Hora de Fin')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('pospuesto', 'Pospuesto')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación')),
                ('enlace_reunion', models.URLField(blank=True, null=True, verbose_name='Enlace de Reunión')),
                ('es_todo_el_dia', models.BooleanField(default=False, verbose_name='Todo el Día')),
                ('recordatorio_minutos', models.IntegerField(default=15, verbose_name='Recordatorio (minutos antes)')),
                ('notas_internas', models.TextField(blank=True, null=True, verbose_name='Notas Internas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('asignado_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado A')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha_inicio', 'prioridad'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='agenda.evento', verbose_name='Evento')),
                ('motivo', models.CharField(choices=[('presentacion', 'Presentación de Productos'), ('seguimiento', 'Seguimiento'), ('cierre_venta', 'Cierre de Venta'), ('soporte', 'Soporte Técnico'), ('reunion_negocios', 'Reunión de Negocios'), ('visita_inspeccion', 'Visita de Inspección'), ('otro', 'Otro')], default='seguimiento', max_length=30, verbose_name='Motivo de la Cita')),
                ('estado_cita', models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistió')], default='programada', max_length=15, verbose_name='Estado de la Cita')),
                ('contacto_cliente', models.CharField(blank=True, max_length=200, null=True, verbose_name='Persona de Contacto')),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto')),
                ('resultado', models.TextField(blank=True, null=True, verbose_name='Resultado de la Cita')),
                ('proxima_accion', models.TextField(blank=True, null=True, verbose_name='Próxima Acción')),
                ('fecha_proxima_accion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Próxima Acción')),
                ('valor_oportunidad', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de la Oportunidad')),
                ('probabilidad_cierre', models.IntegerField(default=50, verbose_name='Probabilidad de Cierre (%)')),
                ('recordatorio_enviado', models.BooleanField(default=False, verbose_name='Recordatorio Enviado')),
                ('confirmacion_enviada', models.BooleanField(default=False, verbose_name='Confirmación Enviada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['evento__fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_recordatorio', models.CharField(choices=[('email', 'Correo Electrónico'), ('notificacion', 'Notificación Push'), ('sms', 'SMS'), ('sistema', 'Notificación del Sistema')], default='sistema', max_length=15, verbose_name='Tipo de Recordatorio')),
                ('minutos_antes', models.IntegerField(default=15, verbose_name='Minutos Antes del Evento')),
                ('enviado', models.BooleanField(default=False, verbose_name='Enviado')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('mensaje', models.TextField(verbose_name='Mensaje del Recordatorio')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='agenda.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='agenda_even_fecha_i_1e4964_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['asignado_a', 'estado'], name='agenda_even_asignad_fa534b_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['tipo_evento', 'prioridad'], name='agenda_even_tipo_ev_a52557_idx'),
        ),
        migrations.AddField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente'),
        ),
    ]
