# Generated by Django 4.2.7 on 2025-11-06 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('agenda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recordatorio',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Destinatario'),
        ),
        migrations.AddField(
            model_name='recordatorio',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='agenda.evento', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='asignado_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado A'),
        ),
        migrations.AddField(
            model_name='evento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='evento',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='agenda_even_fecha_i_1e4964_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['asignado_a', 'estado'], name='agenda_even_asignad_fa534b_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['tipo_evento', 'prioridad'], name='agenda_even_tipo_ev_a52557_idx'),
        ),
        migrations.AddField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente'),
        ),
    ]
