# Generated by Django 4.2.7 on 2025-11-07 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_rolepermission_role_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre de categoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='está activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'categoría de gasto',
                'verbose_name_plural': 'categorías de gasto',
                'unique_together': {('tenant', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ServiceExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, verbose_name='código')),
                ('tipo', models.CharField(choices=[('Alquiler', 'Alquiler'), ('Luz', 'Luz'), ('Agua', 'Agua'), ('Internet', 'Internet'), ('Teléfono', 'Teléfono'), ('Gas', 'Gas'), ('Otro', 'Otro')], max_length=50, verbose_name='tipo de servicio')),
                ('proveedor', models.CharField(max_length=100, verbose_name='proveedor')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monto')),
                ('fecha_vencimiento', models.DateField(verbose_name='fecha de vencimiento')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='fecha de pago')),
                ('periodo', models.CharField(help_text='Ej: Enero 2025', max_length=50, verbose_name='periodo')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Vencido', 'Vencido')], default='Pendiente', max_length=20, verbose_name='estado')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_expenses', to='finance.expensecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'gasto de servicio',
                'verbose_name_plural': 'gastos de servicio',
                'ordering': ['-fecha_vencimiento'],
                'unique_together': {('tenant', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='PersonalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, verbose_name='código')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre completo')),
                ('cargo', models.CharField(max_length=50, verbose_name='cargo')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='salario base')),
                ('bonificaciones', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='bonificaciones')),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='descuentos')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='fecha de pago')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default='Pendiente', max_length=20, verbose_name='estado')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_expenses', to='finance.expensecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'gasto de personal',
                'verbose_name_plural': 'gastos de personal',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodo_inicio', models.DateField(verbose_name='inicio del periodo')),
                ('periodo_fin', models.DateField(verbose_name='fin del periodo')),
                ('monto_presupuestado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto presupuestado')),
                ('monto_gastado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='monto gastado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance.expensecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'presupuesto',
                'verbose_name_plural': 'presupuestos',
                'unique_together': {('tenant', 'categoria', 'periodo_inicio', 'periodo_fin')},
            },
        ),
    ]
