# Generated by Django 4.2.7 on 2025-11-02 17:19

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('role', models.CharField(choices=[('super_admin', 'Super Administrador'), ('admin', 'Administrador'), ('manager', 'Gerente'), ('employee', 'Empleado'), ('photographer', 'Fotógrafo'), ('assistant', 'Asistente')], default='employee', max_length=20, verbose_name='Rol')),
                ('is_new_user', models.BooleanField(default=True, verbose_name='Usuario Nuevo')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email Verificado')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Clave')),
                ('value', models.TextField(verbose_name='Valor')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Estudio')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_users', models.IntegerField(default=10, verbose_name='Máximo de Usuarios')),
                ('max_storage_mb', models.IntegerField(default=1000, verbose_name='Almacenamiento Máximo (MB)')),
                ('business_name', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('business_address', models.TextField(verbose_name='Dirección')),
                ('business_phone', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('business_email', models.EmailField(max_length=254, verbose_name='Email Corporativo')),
                ('business_ruc', models.CharField(max_length=11, verbose_name='RUC')),
                ('currency', models.CharField(choices=[('PEN', 'Soles (S/)'), ('USD', 'Dólares ($)'), ('EUR', 'Euros (€)')], default='PEN', max_length=10, verbose_name='Moneda')),
                ('location_type', models.CharField(choices=[('lima', 'Lima - Acceso Completo'), ('provincia', 'Provincia - Acceso Limitado')], default='lima', max_length=20, verbose_name='Tipo de Ubicación')),
            ],
            options={
                'verbose_name': 'Estudio Fotográfico',
                'verbose_name_plural': 'Estudios Fotográficos',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=10, verbose_name='Idioma')),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro')], default='light', max_length=10, verbose_name='Tema')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notificaciones Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('create', 'Crear registro'), ('update', 'Actualizar registro'), ('delete', 'Eliminar registro'), ('export', 'Exportar datos'), ('config_change', 'Cambio de configuración')], max_length=20, verbose_name='Acción')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('module', models.CharField(blank=True, max_length=50, verbose_name='Módulo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Actividad de Usuario',
                'verbose_name_plural': 'Actividades de Usuario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Estudio Fotográfico'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='TenantConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('general', 'General'), ('crm', 'CRM'), ('commerce', 'Commerce'), ('operations', 'Operations'), ('finance', 'Finance'), ('analytics', 'Analytics')], max_length=20, verbose_name='Módulo')),
                ('key', models.CharField(max_length=100, verbose_name='Clave')),
                ('value', models.TextField(verbose_name='Valor')),
                ('data_type', models.CharField(choices=[('string', 'Texto'), ('integer', 'Número entero'), ('float', 'Número decimal'), ('boolean', 'Verdadero/Falso'), ('json', 'JSON')], default='string', max_length=20, verbose_name='Tipo de dato')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_editable', models.BooleanField(default=True, verbose_name='Editable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Configuración del Tenant',
                'verbose_name_plural': 'Configuraciones del Tenant',
                'unique_together': {('tenant', 'module', 'key')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Administrador'), ('admin', 'Administrador'), ('manager', 'Gerente'), ('employee', 'Empleado'), ('photographer', 'Fotógrafo'), ('assistant', 'Asistente')], max_length=20, verbose_name='Rol')),
                ('access_dashboard', models.BooleanField(default=True, verbose_name='Dashboard')),
                ('access_agenda', models.BooleanField(default=True, verbose_name='Agenda')),
                ('access_pedidos', models.BooleanField(default=True, verbose_name='Pedidos')),
                ('access_clientes', models.BooleanField(default=True, verbose_name='Clientes')),
                ('access_inventario', models.BooleanField(default=False, verbose_name='Inventario')),
                ('access_activos', models.BooleanField(default=False, verbose_name='Activos')),
                ('access_gastos', models.BooleanField(default=False, verbose_name='Gastos')),
                ('access_produccion', models.BooleanField(default=False, verbose_name='Producción')),
                ('access_contratos', models.BooleanField(default=False, verbose_name='Contratos')),
                ('access_reportes', models.BooleanField(default=False, verbose_name='Reportes')),
                ('view_costos', models.BooleanField(default=False, verbose_name='Ver Costos')),
                ('view_precios', models.BooleanField(default=False, verbose_name='Ver Precios')),
                ('view_margenes', models.BooleanField(default=False, verbose_name='Ver Márgenes')),
                ('view_datos_clientes', models.BooleanField(default=False, verbose_name='Ver Datos de Clientes')),
                ('view_datos_financieros', models.BooleanField(default=False, verbose_name='Ver Datos Financieros')),
                ('edit_precios', models.BooleanField(default=False, verbose_name='Editar Precios')),
                ('delete_registros', models.BooleanField(default=False, verbose_name='Eliminar Registros')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Roles',
                'unique_together': {('tenant', 'role')},
            },
        ),
    ]
