# Generated by Django 4.2.16 on 2025-11-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_migrate_user_roles_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrador'), ('admin', 'Administrador'), ('manager', 'Gerente'), ('employee', 'Empleado'), ('photographer', 'Fotógrafo'), ('assistant', 'Asistente')], max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrador'), ('admin', 'Administrador'), ('manager', 'Gerente'), ('employee', 'Empleado'), ('photographer', 'Fotógrafo'), ('assistant', 'Asistente')], default='employee', max_length=20, verbose_name='Rol'),
        ),
    ]
