# Generated by Django 4.2.7 on 2025-11-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_rolepermission_role_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[], max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrador'), ('admin', 'Administrador'), ('ventas', 'Ventas'), ('produccion', 'Producción'), ('operario', 'Operario')], default='operario', max_length=20, verbose_name='Rol'),
        ),
    ]
