# Generated by Django 4.2.7 on 2025-11-06 21:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('impresora', 'Impresora'), ('equipo de oficina', 'Equipo de Oficina'), ('maquinaria', 'Maquinaria'), ('herramienta', 'Herramienta'), ('vehiculo', 'Vehículo')], max_length=50)),
                ('proveedor', models.CharField(max_length=255)),
                ('fecha_compra', models.DateField()),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_pago', models.CharField(choices=[('contado', 'Contado'), ('financiado', 'Financiado'), ('leasing', 'Leasing')], max_length=20)),
                ('vida_util', models.PositiveIntegerField(help_text='Vida útil en meses')),
                ('depreciacion_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('en mantenimiento', 'En Mantenimiento'), ('inactivo', 'Inactivo')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('insumos impresoras', 'Insumos Impresoras'), ('repuestos impresoras', 'Repuestos Impresoras'), ('insumos camaras', 'Insumos Camaras'), ('repuestos camaras', 'Repuestos Camaras'), ('herramientas', 'Herramientas'), ('otros', 'Otros')], default='general', max_length=20)),
                ('ubicacion', models.CharField(choices=[('almacen A', 'Almacen A'), ('almacen B', 'Almacen B'), ('estanteria 1', 'Estanteria 1'), ('estanteria 2', 'Estanteria B'), ('bodega', 'Bodega')], default='almacen A', max_length=20)),
                ('proveedor', models.CharField(max_length=255)),
                ('codigo', models.CharField(default='0000000000', max_length=255)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descripcion', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('emergencia', 'Emergencia')], max_length=20)),
                ('fecha_mantenimiento', models.DateField()),
                ('proveedor', models.CharField(max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado_del_mantenimiento', models.CharField(choices=[('programado', 'Programado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('estado_del_activo', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'Mantenimiento')], default='activo', max_length=20)),
                ('proxima_fecha_mantenimiento', models.DateField(default=datetime.date.today)),
                ('descripcion', models.TextField()),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='activos.activo')),
            ],
        ),
        migrations.CreateModel(
            name='Financiamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('financiado', 'Financiado'), ('leasing', 'Leasing')], max_length=20)),
                ('entidad_financiera', models.CharField(max_length=255)),
                ('monto_financiado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuotas_totales', models.PositiveIntegerField()),
                ('cuota_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pagado', 'Pagado'), ('mora', 'Mora')], max_length=20)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financiamientos', to='activos.activo')),
            ],
        ),
    ]
