# Generated by Django 4.2.7 on 2025-11-06 21:02

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multitenancy', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('role', models.CharField(choices=[('super_admin', 'Super Administrador'), ('admin', 'Administrador'), ('ventas', 'Ventas'), ('produccion', 'Producción'), ('operario', 'Operario')], default='operario', max_length=20, verbose_name='Rol')),
                ('is_new_user', models.BooleanField(default=True, verbose_name='Usuario Nuevo')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email Verificado')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multitenancy.tenant', verbose_name='Estudio Fotográfico')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Administrador'), ('admin', 'Administrador'), ('ventas', 'Ventas'), ('produccion', 'Producción'), ('operario', 'Operario')], max_length=20, verbose_name='Rol')),
                ('access_dashboard', models.BooleanField(default=True, verbose_name='Dashboard')),
                ('access_agenda', models.BooleanField(default=True, verbose_name='Agenda')),
                ('access_pedidos', models.BooleanField(default=True, verbose_name='Pedidos')),
                ('access_clientes', models.BooleanField(default=True, verbose_name='Clientes')),
                ('access_inventario', models.BooleanField(default=False, verbose_name='Inventario')),
                ('access_activos', models.BooleanField(default=False, verbose_name='Activos')),
                ('access_gastos', models.BooleanField(default=False, verbose_name='Gastos')),
                ('access_produccion', models.BooleanField(default=False, verbose_name='Producción')),
                ('access_contratos', models.BooleanField(default=False, verbose_name='Contratos')),
                ('access_reportes', models.BooleanField(default=False, verbose_name='Reportes')),
                ('view_costos', models.BooleanField(default=False, verbose_name='Ver Costos')),
                ('view_precios', models.BooleanField(default=False, verbose_name='Ver Precios')),
                ('view_margenes', models.BooleanField(default=False, verbose_name='Ver Márgenes')),
                ('view_datos_clientes', models.BooleanField(default=False, verbose_name='Ver Datos de Clientes')),
                ('view_datos_financieros', models.BooleanField(default=False, verbose_name='Ver Datos Financieros')),
                ('edit_precios', models.BooleanField(default=False, verbose_name='Editar Precios')),
                ('delete_registros', models.BooleanField(default=False, verbose_name='Eliminar Registros')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multitenancy.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Roles',
                'unique_together': {('tenant', 'role')},
            },
        ),
    ]
