# Generated by Django 4.2.7 on 2025-11-06 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multitenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('product_type', models.CharField(choices=[('product', 'Producto'), ('service', 'Servicio')], default='product', max_length=20, verbose_name='Tipo')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de Costo')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Stock Disponible')),
                ('min_stock', models.IntegerField(default=0, verbose_name='Stock Mínimo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multitenancy.tenant', verbose_name='Estudio Fotográfico')),
            ],
            options={
                'verbose_name': 'Producto/Servicio (Legacy)',
                'verbose_name_plural': 'Productos/Servicios (Legacy)',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
