# Generated by Django 5.2.6 on 2025-11-05 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_rolepermission_role_alter_user_role'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, verbose_name='Número de Pedido')),
                ('document_type', models.CharField(choices=[('proforma', 'Proforma'), ('nota_venta', 'Nota de Venta'), ('contrato', 'Contrato')], max_length=20, verbose_name='Tipo de Documento')),
                ('client_type', models.CharField(choices=[('particular', 'Particular'), ('colegio', 'Colegio'), ('empresa', 'Empresa')], max_length=20, verbose_name='Tipo de Cliente')),
                ('school_level', models.CharField(blank=True, choices=[('inicial', 'Inicial'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria')], max_length=20, null=True, verbose_name='Nivel (Colegios)')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grado')),
                ('section', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sección')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('delivery_date', models.DateField(verbose_name='Fecha de Entrega')),
                ('scheduled_dates', models.JSONField(blank=True, default=dict, help_text='Contiene sesiones_fotograficas y entregas como listas de objetos con fecha y hora', verbose_name='Fechas Programadas')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IGV')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='A Cuenta')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo')),
                ('extra_services', models.TextField(blank=True, verbose_name='Servicios Extras')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('affects_inventory', models.BooleanField(default=False, verbose_name='Afecta Inventario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm.client', verbose_name='Cliente')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='crm.contract', verbose_name='Contrato Relacionado')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Estudio Fotográfico')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200, verbose_name='Nombre del Producto/Servicio')),
                ('product_description', models.TextField(blank=True, verbose_name='Descripción')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('affects_inventory', models.BooleanField(default=False, verbose_name='Afecta Inventario')),
                ('inventory_item_id', models.IntegerField(blank=True, null=True, verbose_name='ID de Item de Inventario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.order', verbose_name='Pedido')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Estudio Fotográfico')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('product_type', models.CharField(choices=[('product', 'Producto'), ('service', 'Servicio')], default='product', max_length=20, verbose_name='Tipo')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de Costo')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Stock Disponible')),
                ('min_stock', models.IntegerField(default=0, verbose_name='Stock Mínimo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Estudio Fotográfico')),
            ],
            options={
                'verbose_name': 'Producto/Servicio',
                'verbose_name_plural': 'Productos/Servicios',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
