# Generated by Django 4.2.7 on 2025-11-06 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multitenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cliente', models.CharField(choices=[('particular', 'Particular'), ('colegio', 'Colegio'), ('empresa', 'Empresa')], default='particular', max_length=20, verbose_name='Tipo de Cliente')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('dni', models.CharField(max_length=15, unique=True, verbose_name='DNI/RUC')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('nivel_educativo', models.CharField(blank=True, choices=[('inicial', 'Inicial'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria')], max_length=20, null=True, verbose_name='Nivel (Colegios)')),
                ('grado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grado (Colegios)')),
                ('seccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sección (Colegios)')),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multitenancy.tenant', verbose_name='Estudio Fotográfico')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellidos', 'nombres'],
                'unique_together': {('tenant', 'dni')},
            },
        ),
        migrations.CreateModel(
            name='HistorialCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_interaccion', models.CharField(choices=[('llamada', 'Llamada Telefónica'), ('email', 'Correo Electrónico'), ('reunion', 'Reunión Presencial'), ('whatsapp', 'WhatsApp'), ('visita', 'Visita al Estudio'), ('evento', 'Evento/Sesión'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('resultado', models.TextField(blank=True, verbose_name='Resultado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='clientes.cliente')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por')),
            ],
            options={
                'verbose_name': 'Historial de Cliente',
                'verbose_name_plural': 'Historiales de Cliente',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Contacto')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Contacto Principal')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Contacto de Cliente',
                'verbose_name_plural': 'Contactos de Cliente',
                'ordering': ['-es_principal', 'nombre'],
            },
        ),
    ]
