# Generated by Django 4.2.16 on 2025-11-04 22:52

import apps.crm.clientes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_rolepermission_role_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('tipo_cliente', models.CharField(choices=[('particular', 'Particular'), ('colegio', 'Colegio'), ('empresa', 'Empresa')], default='particular', max_length=20)),
                ('dni', models.CharField(blank=True, help_text='Requerido para clientes particulares (8 dígitos)', max_length=15, null=True, validators=[apps.crm.clientes.models.validar_dni])),
                ('ruc', models.CharField(blank=True, help_text='Requerido para empresas y colegios (11 dígitos)', max_length=11, null=True, validators=[apps.crm.clientes.models.validar_ruc])),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('institucion_educativa', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('detalles_adicionales', models.TextField(blank=True, null=True)),
                ('pedidos', models.PositiveIntegerField(default=0)),
                ('total_gastado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ultima_fecha_pedido', models.DateField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('dni__isnull', False), models.Q(('dni', ''), _negated=True)), fields=('tenant', 'dni'), name='unique_tenant_dni_when_not_null'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('ruc__isnull', False), models.Q(('ruc', ''), _negated=True)), fields=('tenant', 'ruc'), name='unique_tenant_ruc_when_not_null'),
        ),
    ]
