# Generated by Django 4.2.16 on 2025-11-04 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial_simple_ids'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cliente',
            name='unique_dni_when_not_null',
        ),
        migrations.RemoveConstraint(
            model_name='cliente',
            name='unique_ruc_when_not_null',
        ),
        migrations.AddField(
            model_name='cliente',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('dni__isnull', False), models.Q(('dni', ''), _negated=True)), fields=('tenant', 'dni'), name='unique_tenant_dni_when_not_null'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('ruc__isnull', False), models.Q(('ruc', ''), _negated=True)), fields=('tenant', 'ruc'), name='unique_tenant_ruc_when_not_null'),
        ),
    ]
