# Generated by Django 5.2.6 on 2025-11-05 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_rolepermission_role_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_type', models.CharField(choices=[('particular', 'Particular'), ('colegio', 'Colegio'), ('empresa', 'Empresa')], default='particular', max_length=20, verbose_name='Tipo de Cliente')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('dni', models.CharField(max_length=15, unique=True, verbose_name='DNI/RUC')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('school_level', models.CharField(blank=True, choices=[('inicial', 'Inicial'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria')], max_length=20, null=True, verbose_name='Nivel (Colegios)')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grado (Colegios)')),
                ('section', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sección (Colegios)')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Estudio Fotográfico')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('tenant', 'dni')},
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=50, verbose_name='Número de Contrato')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Contrato')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='crm.client', verbose_name='Cliente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Estudio Fotográfico')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'contract_number')},
            },
        ),
    ]
