# Generated by Django 4.2.16 on 2025-11-04 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('core', '0004_alter_rolepermission_role_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=160)),
                ('contract_type', models.CharField(choices=[('PHOTO', 'Servicio Fotografía'), ('FRAME', 'Enmarcado'), ('GRAD', 'Graduaciones'), ('LASER', 'Corte Láser'), ('EVENT', 'Evento'), ('CUSTOM', 'Personalizado')], max_length=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING', 'Pendiente Aprobación'), ('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido'), ('COMPLETED', 'Completado'), ('CANCELED', 'Cancelado')], db_index=True, default='DRAFT', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, upload_to='contracts/')),
                ('external_ref', models.CharField(blank=True, max_length=64)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_contracts', to='clientes.cliente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crm_contracts', to='core.tenant')),
            ],
            options={
                'db_table': 'crm_contract',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='crm_contrac_tenant__c4146f_idx'), models.Index(fields=['tenant', 'contract_type'], name='crm_contrac_tenant__42af88_idx')],
            },
        ),
    ]
