# Generated by Django 4.2.7 on 2025-11-06 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multitenancy', '0001_initial'),
        ('clientes', '0001_initial'),
        ('contratos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, verbose_name='Número de Pedido')),
                ('document_type', models.CharField(choices=[('proforma', 'Proforma'), ('nota_venta', 'Nota de Venta'), ('contrato', 'Contrato')], max_length=20, verbose_name='Tipo de Documento')),
                ('client_type', models.CharField(choices=[('particular', 'Particular'), ('colegio', 'Colegio'), ('empresa', 'Empresa')], max_length=20, verbose_name='Tipo de Cliente')),
                ('school_level', models.CharField(blank=True, choices=[('inicial', 'Inicial'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria')], max_length=20, null=True, verbose_name='Nivel (Colegios)')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grado')),
                ('section', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sección')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Pedido')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('delivery_date', models.DateField(verbose_name='Fecha de Entrega')),
                ('scheduled_dates', models.JSONField(blank=True, default=dict, help_text='Contiene sesiones_fotograficas y entregas como listas de objetos con fecha y hora', verbose_name='Fechas Programadas')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Dirección de Entrega')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='Notas de Entrega')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IGV')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Pagado')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Pendiente')),
                ('payment_status', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Pago Parcial'), ('completo', 'Pagado Completo')], default='pendiente', max_length=20, verbose_name='Estado de Pago')),
                ('extra_services', models.TextField(blank=True, verbose_name='Servicios Extras')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('description', models.TextField(blank=True, verbose_name='Descripción del Pedido')),
                ('affects_inventory', models.BooleanField(default=False, verbose_name='Afecta Inventario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='clientes.cliente', verbose_name='Cliente')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='contratos.contrato', verbose_name='Contrato Relacionado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multitenancy.tenant', verbose_name='Estudio Fotográfico')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], max_length=20, verbose_name='Estado Anterior')),
                ('new_status', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], max_length=20, verbose_name='Estado Nuevo')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo del Cambio')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado Por')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='pedidos.order')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Fecha de Pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('payment_method', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('yape', 'Yape'), ('plin', 'Plin'), ('cheque', 'Cheque'), ('otro', 'Otro')], max_length=20, verbose_name='Método de Pago')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pedidos.order')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por')),
            ],
            options={
                'verbose_name': 'Pago de Pedido',
                'verbose_name_plural': 'Pagos de Pedido',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200, verbose_name='Nombre del Producto/Servicio')),
                ('product_description', models.TextField(blank=True, verbose_name='Descripción')),
                ('product_code', models.CharField(blank=True, max_length=50, verbose_name='Código del Producto')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('affects_inventory', models.BooleanField(default=False, verbose_name='Afecta Inventario')),
                ('inventory_item_id', models.IntegerField(blank=True, null=True, verbose_name='ID de Item de Inventario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.order', verbose_name='Pedido')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multitenancy.tenant', verbose_name='Estudio Fotográfico')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
                'ordering': ['created_at'],
            },
        ),
    ]
