# Generated by Django 4.2.7 on 2025-11-06 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Estudio')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_users', models.IntegerField(default=10, verbose_name='Máximo de Usuarios')),
                ('max_storage_mb', models.IntegerField(default=1000, verbose_name='Almacenamiento Máximo (MB)')),
                ('business_name', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('business_address', models.TextField(verbose_name='Dirección')),
                ('business_phone', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('business_email', models.EmailField(max_length=254, verbose_name='Email Corporativo')),
                ('business_ruc', models.CharField(max_length=11, verbose_name='RUC')),
                ('currency', models.CharField(choices=[('PEN', 'Soles (S/)'), ('USD', 'Dólares ($)'), ('EUR', 'Euros (€)')], default='PEN', max_length=10, verbose_name='Moneda')),
                ('location_type', models.CharField(choices=[('lima', 'Lima - Acceso Completo'), ('provincia', 'Provincia - Acceso Limitado')], default='lima', max_length=20, verbose_name='Tipo de Ubicación')),
            ],
            options={
                'verbose_name': 'Estudio Fotográfico',
                'verbose_name_plural': 'Estudios Fotográficos',
            },
        ),
        migrations.CreateModel(
            name='TenantConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('general', 'General'), ('crm', 'CRM'), ('commerce', 'Commerce'), ('operations', 'Operations'), ('finance', 'Finance'), ('analytics', 'Analytics')], max_length=20, verbose_name='Módulo')),
                ('key', models.CharField(max_length=100, verbose_name='Clave')),
                ('value', models.TextField(verbose_name='Valor')),
                ('data_type', models.CharField(choices=[('string', 'Texto'), ('integer', 'Número entero'), ('float', 'Número decimal'), ('boolean', 'Verdadero/Falso'), ('json', 'JSON')], default='string', max_length=20, verbose_name='Tipo de dato')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_editable', models.BooleanField(default=True, verbose_name='Editable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multitenancy.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Configuración del Tenant',
                'verbose_name_plural': 'Configuraciones del Tenant',
                'unique_together': {('tenant', 'module', 'key')},
            },
        ),
    ]
